In [48]:
import numpy as np

input_size = 3
neuron_number = 4

inputs = np.random.rand(input_size)
biases = np.random.rand(neuron_number)
weights = np.random.rand(neuron_number, input_size)

outputs = []

print(inputs, biases, weights)

[0.11994447 0.81654209 0.68614579] [0.46787285 0.02217175 0.57822525 0.07887799] [[0.90486648 0.64914063 0.27102502]
 [0.81805523 0.2060596  0.03429693]
 [0.48500975 0.70475528 0.09312462]
 [0.5548043  0.83458166 0.5058227 ]]


In [44]:
#METHOD 1: coding our first neurons not using numpy.
#neural network with three neurons and two inputs:
import numpy as np
neuron_number = 2
inputs = [3,5,6,7]
weights = [[4,6,2,0],[3,6,3,2]]
biases = [3,5]
outputs = []
for neuron_weights, neuron_bias in zip(weights, biases):
    print(neuron_weights,neuron_bias)
    neuron_output = 0
    for elem, weight in zip (inputs, neuron_weights):
        neuron_output =+ elem*weight
    neuron_output =+ neuron_bias
    outputs.append(neuron_output)
print(outputs)


[3, 5]


In [45]:
#METHOD2: using numpy dot product
outputs2 = []

neuron_number = 2
inputs = [3,5,6,7]
weights = [[4,6,2,0],[3,6,3,2]]
biases = [3,5]
for i in range(neuron_number):
    output = np.dot(weights[i], inputs) + biases[i]
    outputs2.append(output)
outputs2

[57, 76]

In [47]:
rana = [3,2]